del /s *.aux 
del /s *.idx 
del /s *.blg
del /s *.bbl
del /s *.fls  
del /s *.out
del /s *.out.bak
del /s *.toc 
del /s *.nav 
del /s *.snm 
del /s *.vrb 
del /s *.dvi 
del /s *.fdb_latexmk
del /s *.log 
del /s *.synctex.gz
del /s *.synctex
del /s *.synctex(busy)
del /s *.latexmkrc
del /s *.bcf
del /s *.lof
del /s *.lot
del /s *.xml
del /s main-blx.bib
